// Generated by CoffeeScript 1.3.3
(function() {

  define(['module'], function(module) {
    var keyframes;
    keyframes = {
      set: function($el, frames, duration) {
        var animate;
        animate = function() {
          var spendTime;
          spendTime = 0;
          $el.stop(true);
          $.each(frames, function(idx, val) {
            var stepDuration, stepPercentage;
            stepPercentage = idx.replace('%', '') / 100;
            stepDuration = duration * stepPercentage - spendTime;
            $el.animate(val, stepDuration);
            return spendTime += stepDuration;
          });
          return setTimeout(animate, duration);
        };
        return animate();
      }
    };
    return keyframes;
  });

}).call(this);
